from typing import Literal

from sqlalchemy.orm import Session

from app.models.covered_call import CoveredCall
from app.services.options_query import OptionsSortField, build_options_query

CoveredCallSortField = OptionsSortField


def get_covered_calls(
    db: Session,
    exchange: int | None = None,
    ticker: str | None = None,
    contract: str | None = None,
    min_expiry: str | None = None,
    days_to_expiration_min: int | None = None,
    days_to_expiration_max: int | None = None,
    option_yield_min: float | None = None,
    option_yield_max: float | None = None,
    roc_min: float | None = None,
    roc_max: float | None = None,
    tot_return_min: float | None = None,
    tot_return_max: float | None = None,
    premium_per_contract_min: float | None = None,
    premium_per_contract_max: float | None = None,
    open_interest_min: int | None = None,
    open_interest_max: int | None = None,
    impl_volatility_min: float | None = None,
    impl_volatility_max: float | None = None,
    delta_min: float | None = None,
    delta_max: float | None = None,
    moneyness_min: float | None = None,
    moneyness_max: float | None = None,
    spread_bid_ask_min: float | None = None,
    spread_bid_ask_max: float | None = None,
    sector: str | None = None,
    industry: str | None = None,
    sort_by: CoveredCallSortField | None = None,
    sort_dir: Literal["asc", "desc"] = "desc",
    limit: int = 50,
    offset: int = 0,
):
    return build_options_query(
        db=db,
        model=CoveredCall,
        exchange=exchange,
        ticker=ticker,
        contract=contract,
        min_expiry=min_expiry,
        days_to_expiration_min=days_to_expiration_min,
        days_to_expiration_max=days_to_expiration_max,
        option_yield_min=option_yield_min,
        option_yield_max=option_yield_max,
        roc_min=roc_min,
        roc_max=roc_max,
        tot_return_min=tot_return_min,
        tot_return_max=tot_return_max,
        premium_per_contract_min=premium_per_contract_min,
        premium_per_contract_max=premium_per_contract_max,
        open_interest_min=open_interest_min,
        open_interest_max=open_interest_max,
        impl_volatility_min=impl_volatility_min,
        impl_volatility_max=impl_volatility_max,
        delta_min=delta_min,
        delta_max=delta_max,
        moneyness_min=moneyness_min,
        moneyness_max=moneyness_max,
        spread_bid_ask_min=spread_bid_ask_min,
        spread_bid_ask_max=spread_bid_ask_max,
        sector=sector,
        industry=industry,
        sort_by=sort_by,
        sort_dir=sort_dir,
        limit=limit,
        offset=offset,
    )
