"""initial schema

Revision ID: 522f47e06099
Revises: 
Create Date: 2026-01-03 21:29:58.662859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522f47e06099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EXCHANGE',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('exchange_id'),
    sa.UniqueConstraint('exchange_name')
    )
    op.create_index(op.f('ix_EXCHANGE_exchange_id'), 'EXCHANGE', ['exchange_id'], unique=False)
    op.create_table('INDUSTRY',
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('industry_id')
    )
    op.create_index(op.f('ix_INDUSTRY_industry_name'), 'INDUSTRY', ['industry_name'], unique=True)
    op.create_table('SECTOR',
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('sector_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sector_id')
    )
    op.create_index(op.f('ix_SECTOR_sector_name'), 'SECTOR', ['sector_name'], unique=True)
    op.create_table('TREND',
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('trend_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('trend_id')
    )
    op.create_index(op.f('ix_TREND_trend_name'), 'TREND', ['trend_name'], unique=True)
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USERS_email'), 'USERS', ['email'], unique=True)
    op.create_table('BEST_COVERED_CALLS',
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('exchange', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exchange'], ['EXCHANGE.exchange_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contract')
    )
    op.create_index(op.f('ix_BEST_COVERED_CALLS_contract'), 'BEST_COVERED_CALLS', ['contract'], unique=False)
    op.create_index(op.f('ix_BEST_COVERED_CALLS_expiry_date'), 'BEST_COVERED_CALLS', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_BEST_COVERED_CALLS_ticker'), 'BEST_COVERED_CALLS', ['ticker'], unique=False)
    op.create_index('ix_covered_calls_ticker_expiry', 'BEST_COVERED_CALLS', ['ticker', 'expiry_date'], unique=False)
    op.create_table('BEST_PUT_OPTIONS',
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('exchange', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exchange'], ['EXCHANGE.exchange_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contract')
    )
    op.create_index(op.f('ix_BEST_PUT_OPTIONS_contract'), 'BEST_PUT_OPTIONS', ['contract'], unique=False)
    op.create_index(op.f('ix_BEST_PUT_OPTIONS_expiry_date'), 'BEST_PUT_OPTIONS', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_BEST_PUT_OPTIONS_ticker'), 'BEST_PUT_OPTIONS', ['ticker'], unique=False)
    op.create_index('ix_put_options_ticker_expiry', 'BEST_PUT_OPTIONS', ['ticker', 'expiry_date'], unique=False)
    op.create_table('BEST_SPREAD_OPTIONS',
    sa.Column('contract', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('exchange', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exchange'], ['EXCHANGE.exchange_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contract')
    )
    op.create_index(op.f('ix_BEST_SPREAD_OPTIONS_contract'), 'BEST_SPREAD_OPTIONS', ['contract'], unique=False)
    op.create_index(op.f('ix_BEST_SPREAD_OPTIONS_expiry_date'), 'BEST_SPREAD_OPTIONS', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_BEST_SPREAD_OPTIONS_ticker'), 'BEST_SPREAD_OPTIONS', ['ticker'], unique=False)
    op.create_index('ix_spread_options_ticker_expiry', 'BEST_SPREAD_OPTIONS', ['ticker', 'expiry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spread_options_ticker_expiry', table_name='BEST_SPREAD_OPTIONS')
    op.drop_index(op.f('ix_BEST_SPREAD_OPTIONS_ticker'), table_name='BEST_SPREAD_OPTIONS')
    op.drop_index(op.f('ix_BEST_SPREAD_OPTIONS_expiry_date'), table_name='BEST_SPREAD_OPTIONS')
    op.drop_index(op.f('ix_BEST_SPREAD_OPTIONS_contract'), table_name='BEST_SPREAD_OPTIONS')
    op.drop_table('BEST_SPREAD_OPTIONS')
    op.drop_index('ix_put_options_ticker_expiry', table_name='BEST_PUT_OPTIONS')
    op.drop_index(op.f('ix_BEST_PUT_OPTIONS_ticker'), table_name='BEST_PUT_OPTIONS')
    op.drop_index(op.f('ix_BEST_PUT_OPTIONS_expiry_date'), table_name='BEST_PUT_OPTIONS')
    op.drop_index(op.f('ix_BEST_PUT_OPTIONS_contract'), table_name='BEST_PUT_OPTIONS')
    op.drop_table('BEST_PUT_OPTIONS')
    op.drop_index('ix_covered_calls_ticker_expiry', table_name='BEST_COVERED_CALLS')
    op.drop_index(op.f('ix_BEST_COVERED_CALLS_ticker'), table_name='BEST_COVERED_CALLS')
    op.drop_index(op.f('ix_BEST_COVERED_CALLS_expiry_date'), table_name='BEST_COVERED_CALLS')
    op.drop_index(op.f('ix_BEST_COVERED_CALLS_contract'), table_name='BEST_COVERED_CALLS')
    op.drop_table('BEST_COVERED_CALLS')
    op.drop_index(op.f('ix_USERS_email'), table_name='USERS')
    op.drop_table('USERS')
    op.drop_index(op.f('ix_TREND_trend_name'), table_name='TREND')
    op.drop_table('TREND')
    op.drop_index(op.f('ix_SECTOR_sector_name'), table_name='SECTOR')
    op.drop_table('SECTOR')
    op.drop_index(op.f('ix_INDUSTRY_industry_name'), table_name='INDUSTRY')
    op.drop_table('INDUSTRY')
    op.drop_index(op.f('ix_EXCHANGE_exchange_id'), table_name='EXCHANGE')
    op.drop_table('EXCHANGE')
    # ### end Alembic commands ###
