"""add refresh sessions

Revision ID: 6a85c86ff875
Revises: add_refresh_sessions_001
Create Date: 2026-03-24 19:29:56.182485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a85c86ff875'
down_revision: Union[str, Sequence[str], None] = 'add_refresh_sessions_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('BEST_COVERED_CALLS', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_BEST_COVERED_CALLS_contract'), table_name='BEST_COVERED_CALLS')
    op.drop_index(op.f('ix_covered_calls_ticker_expiry'), table_name='BEST_COVERED_CALLS')
    op.create_index('ix_cc_exchange_ticker_expiry', 'BEST_COVERED_CALLS', ['exchange', 'ticker', 'expiry_date'], unique=False)
    op.create_index('ix_cc_exchange_ticker_expiry_contract', 'BEST_COVERED_CALLS', ['exchange', 'ticker', 'expiry_date', 'contract'], unique=False)
    op.create_index('ix_cc_ticker_expiry', 'BEST_COVERED_CALLS', ['ticker', 'expiry_date'], unique=False)
    op.alter_column('BEST_PUT_OPTIONS', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_BEST_PUT_OPTIONS_contract'), table_name='BEST_PUT_OPTIONS')
    op.drop_index(op.f('ix_put_options_ticker_expiry'), table_name='BEST_PUT_OPTIONS')
    op.create_index('ix_po_exchange_ticker_expiry', 'BEST_PUT_OPTIONS', ['exchange', 'ticker', 'expiry_date'], unique=False)
    op.create_index('ix_po_exchange_ticker_expiry_contract', 'BEST_PUT_OPTIONS', ['exchange', 'ticker', 'expiry_date', 'contract'], unique=False)
    op.create_index('ix_po_ticker_expiry', 'BEST_PUT_OPTIONS', ['ticker', 'expiry_date'], unique=False)
    op.alter_column('BEST_SPREAD_OPTIONS', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_BEST_SPREAD_OPTIONS_contract'), table_name='BEST_SPREAD_OPTIONS')
    op.drop_index(op.f('ix_spread_options_ticker_expiry'), table_name='BEST_SPREAD_OPTIONS')
    op.create_index('ix_so_exchange_ticker_expiry', 'BEST_SPREAD_OPTIONS', ['exchange', 'ticker', 'expiry_date'], unique=False)
    op.create_index('ix_so_exchange_ticker_expiry_contract', 'BEST_SPREAD_OPTIONS', ['exchange', 'ticker', 'expiry_date', 'contract'], unique=False)
    op.create_index('ix_so_ticker_expiry', 'BEST_SPREAD_OPTIONS', ['ticker', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_id'), 'refresh_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_sessions_id'), table_name='refresh_sessions')
    op.drop_index('ix_so_ticker_expiry', table_name='BEST_SPREAD_OPTIONS')
    op.drop_index('ix_so_exchange_ticker_expiry_contract', table_name='BEST_SPREAD_OPTIONS')
    op.drop_index('ix_so_exchange_ticker_expiry', table_name='BEST_SPREAD_OPTIONS')
    op.create_index(op.f('ix_spread_options_ticker_expiry'), 'BEST_SPREAD_OPTIONS', ['ticker', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_BEST_SPREAD_OPTIONS_contract'), 'BEST_SPREAD_OPTIONS', ['contract'], unique=False)
    op.alter_column('BEST_SPREAD_OPTIONS', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_po_ticker_expiry', table_name='BEST_PUT_OPTIONS')
    op.drop_index('ix_po_exchange_ticker_expiry_contract', table_name='BEST_PUT_OPTIONS')
    op.drop_index('ix_po_exchange_ticker_expiry', table_name='BEST_PUT_OPTIONS')
    op.create_index(op.f('ix_put_options_ticker_expiry'), 'BEST_PUT_OPTIONS', ['ticker', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_BEST_PUT_OPTIONS_contract'), 'BEST_PUT_OPTIONS', ['contract'], unique=False)
    op.alter_column('BEST_PUT_OPTIONS', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_cc_ticker_expiry', table_name='BEST_COVERED_CALLS')
    op.drop_index('ix_cc_exchange_ticker_expiry_contract', table_name='BEST_COVERED_CALLS')
    op.drop_index('ix_cc_exchange_ticker_expiry', table_name='BEST_COVERED_CALLS')
    op.create_index(op.f('ix_covered_calls_ticker_expiry'), 'BEST_COVERED_CALLS', ['ticker', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_BEST_COVERED_CALLS_contract'), 'BEST_COVERED_CALLS', ['contract'], unique=False)
    op.alter_column('BEST_COVERED_CALLS', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
